Updated Python and added prod CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -95,3 +95,92 @@ jobs:
 
             echo "*** Step: ** Cleanup"
             rm -rf ~/projectlab/tmp
+    
+  deploy-prod:
+  name: 🚀 Deploy Prod
+  runs-on: ubuntu-latest
+  environment: prod
+  #needs: [lint, typecheck, vitest, cypress]
+  # only build/deploy prod on new version tags (v1.0.0)
+  if: startsWith(github.ref, 'refs/tags/v')
+
+  env:
+    NODE_ENV: production
+
+  steps:
+    - name: 🛑 Cancel Previous Runs
+      if: ${{ env.GITHUB_ACTOR != 'nektos/act' }}
+      uses: styfle/cancel-workflow-action@0.11.0
+
+    - name: ⬇️ Checkout repo
+      uses: actions/checkout@v3
+
+    - name: Prepare Server For Build
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.LIGHTSAIL_IP_PROD }}
+          username: ${{ secrets.LIGHTSAIL_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            rm -rf ~/itesm-socioformador-ene-feb-2023-equipo-1/tmp
+            mkdir -p ~/itesm-socioformador-ene-feb-2023-equipo-1/tmp
+
+    - name: Copy Files To Lightsail Instance
+        uses: wlixcc/SFTP-Deploy-Action@v1.0
+        with:
+          username: ${{ secrets.LIGHTSAIL_USER }}
+          server: ${{ secrets.LIGHTSAIL_IP_PROD }}
+          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
+          local_path: "./*"
+          remote_path: "/home/admin/itesm-socioformador-ene-feb-2023-equipo-1/tmp"
+          args: "-o ConnectTimeout=60"
+
+    - name: Configure Server
+        uses: appleboy/ssh-action@master
+        env:
+          BASE_URL: ${{ secrets.BASE_URL_PROD }}
+          PORT: ${{ secrets.PORT }}
+          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
+          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
+          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
+          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
+          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
+          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+        with:
+          timeout: 60s
+          command_timeout: 30m
+          envs: BASE_URL_PROD,PORT,DATABASE_URL_PROD,AUTH0_DOMAIN,SESSION_SECRET,AUTH0_CLIENT_ID,AUTH0_CLIENT_SECRET,OPENAI_API_KEY
+          host: ${{ secrets.LIGHTSAIL_IP_PROD }}
+          username: ${{ secrets.LIGHTSAIL_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script_stop: true
+          script: |
+            # ignore failure on pm2 stop (first time?)
+            pm2 stop all || true
+
+            echo "*** Step: *** Replace app folders"
+            rm -rf ~/itesm-socioformador-ene-feb-2023-equipo-1/app
+            mkdir -p ~/itesm-socioformador-ene-feb-2023-equipo-1/app
+            cp -R ~/itesm-socioformador-ene-feb-2023-equipo-1/tmp/. ~/itesm-socioformador-ene-feb-2023-equipo-1/app/
+            cd ~/itesm-socioformador-ene-feb-2023-equipo-1/app
+
+            echo "*** Step: *** Create .env file"
+            echo BASE_URL="$BASE_URL" >> .env
+            echo PORT="$PORT" >> .env
+            echo DATABASE_URL="$DATABASE_URL" >> .env
+            echo SESSION_SECRET="$SESSION_SECRET" >> .env
+            echo AUTH0_CLIENT_ID="$AUTH0_CLIENT_ID" >> .env
+            echo AUTH0_DOMAIN="$AUTH0_DOMAIN" >> .env
+            echo AUTH0_CLIENT_SECRET="$AUTH0_CLIENT_SECRET" >> .env
+            echo OPENAI_API_KEY="$OPENAI_API_KEY" >> .env
+
+            echo "*** Step: *** npm ci and build"
+            npm ci # install
+            npm run build
+
+            echo "*** Step: ** Cleanup"
+            rm -rf ~/projectlab/tmp
+          
+          #echo "*** Step: *** Start pm2 service"
+          #pm2 start ecosystem.config.js
+          #pm2 save
